openapi: 3.0.0
info:
  title: 'Prize API'
  version: 1.0.0
paths:
  /prizes:
    post:
      tags:
        - Prizes
      summary: 'Create a new prize and associate it with a laureate'
      operationId: abbc9a34f094ec797b6c60495b637991
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                laureate_id:
                  description: 'ID of the laureate'
                  type: integer
                year:
                  description: 'Year of the prize'
                  type: string
                category:
                  description: 'Category of the prize'
                  type: string
                contribution_sk:
                  description: 'Contribution in Slovak'
                  type: string
                contribution_en:
                  description: 'Contribution in English'
                  type: string
                language_sk:
                  description: 'Language in Slovak'
                  type: string
                  nullable: true
                language_en:
                  description: 'Language in English'
                  type: string
                  nullable: true
                genre_sk:
                  description: 'Genre in Slovak'
                  type: string
                  nullable: true
                genre_en:
                  description: 'Genre in English'
                  type: string
                  nullable: true
              type: object
      responses:
        '201':
          description: 'Prize created successfully'
          content:
            application/json:
              schema:
                properties:
                  prize_id: { description: 'ID of the created prize', type: integer }
                type: object
        '400':
          description: 'Bad request or database error'
          content:
            application/json:
              schema:
                properties:
                  error: { description: 'Error message', type: string }
                type: object
  '/prizes/{prize_id}':
    delete:
      tags:
        - Prizes
      summary: 'Delete a prize and its associated details'
      operationId: ddf57e5056b4c13c70e1b551d65d79a8
      parameters:
        -
          name: prize_id
          in: path
          description: 'ID of the prize to delete'
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 'Prize deleted successfully'
          content:
            application/json:
              schema:
                properties:
                  message: { type: string, example: 'Prize deleted successfully' }
                type: object
        '404':
          description: 'Prize not found'
          content:
            application/json:
              schema:
                properties:
                  error: { description: 'Error message', type: string }
                type: object
        '400':
          description: 'Bad request or database error'
          content:
            application/json:
              schema:
                properties:
                  error: { description: 'Error message', type: string }
                type: object
tags:
  -
    name: Prizes
    description: Prizes
